---
name: Verify Pull Request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: recursive
    - name: Install Dependencies
      uses: ./.github/actions/install-dependencies
    - name: Compile App
      run: |
        make
    - name: Run App
      run: |
        sudo timeout --preserve-status 5s ./bootstrap
